'use strict'

const COMMENT_BODY_LIMIT = 65_000
const RESERVED_MARKER_RE = /<!--\s*\/?(?:remark|section):/i
const GENERATED_FOOTER = 'Generated by Remark'
const GENERATED_FOOTER_RE = /\n+_Last updated: \d{4}-\d{2}-\d{2} \d{2}:\d{2} UTC - Generated by [Rr]emark_$/

// --- Slug derivation -------------------------------------------------------------------------------------------------

/** Converts an H1 headline text to a URL-safe section key. */
function slugify(text) {
  const raw = String(text ?? '').trim()
  const slug = raw
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')

  if (slug) return slug

  const codepoints = Array.from(raw)
    .filter((ch) => !/\s/u.test(ch))
    .map((ch) => ch.codePointAt(0).toString(16))

  return codepoints.length > 0 ? `h-${codepoints.join('-')}` : ''
}

// --- Markers ---------------------------------------------------------------------------------------------------------

function rootMarker(key) {
  return `<!-- remark:${key} -->`
}

function sectionOpenTag(slug) {
  return `<!-- section:${slug} -->`
}

function sectionCloseTag(slug) {
  return `<!-- /section:${slug} -->`
}

function assertNoReservedMarkers(body) {
  const marker = String(body ?? '').match(RESERVED_MARKER_RE)
  if (marker) {
    throw new Error(`body input contains reserved remark marker syntax near ${JSON.stringify(marker[0])}`)
  }
}

function isGeneratedCommentBody(body, marker) {
  const normalized = String(body ?? '')
    .replace(/\r\n/g, '\n')
    .trimEnd()
  return normalized.startsWith(`${marker}\n`) && GENERATED_FOOTER_RE.test(normalized)
}

// --- Footer ----------------------------------------------------------------------------------------------------------

/** Builds a visible timestamp footer. Accepts an optional Date for testability. */
function buildFooter(now = new Date()) {
  const pad = (n) => String(n).padStart(2, '0')
  const ts = `${now.getUTCFullYear()}-${pad(now.getUTCMonth() + 1)}-${pad(now.getUTCDate())} ${pad(now.getUTCHours())}:${pad(now.getUTCMinutes())} UTC`
  return `_Last updated: ${ts} - ${GENERATED_FOOTER}_`
}

function normalizeForComparison(body) {
  return String(body ?? '')
    .replace(/\r\n/g, '\n')
    .trimEnd()
    .replace(GENERATED_FOOTER_RE, '')
}

function sameGeneratedContent(a, b) {
  return normalizeForComparison(a) === normalizeForComparison(b)
}

// --- Section parsing -------------------------------------------------------------------------------------------------

/**
 * Parses H1-delimited sections from an incoming body (no markers yet).
 * Returns null when no H1 headlines are found (whole-body replacement applies).
 * Throws on an empty slug or a duplicate slug.
 *
 * @param {string} body
 * @returns {Array<{slug: string, content: string}>|null}
 */
function parseSections(body) {
  const lines = String(body ?? '').split('\n')
  const sections = []
  let currentSlug = null
  let currentLines = []

  for (const line of lines) {
    const m = line.match(/^#\s+(.+)/)
    if (m) {
      if (currentSlug !== null) {
        sections.push({ slug: currentSlug, content: currentLines.join('\n').trimEnd() })
      }
      const slug = slugify(m[1])
      if (!slug) throw new Error(`H1 headline "${m[1].trim()}" produces an empty slug after slugification`)
      if (sections.some((s) => s.slug === slug)) {
        throw new Error(`duplicate section slug "${slug}" -- H1 headlines must produce unique slugs`)
      }
      currentSlug = slug
      currentLines = [line]
    } else {
      currentLines.push(line)
    }
  }

  if (currentSlug !== null) {
    sections.push({ slug: currentSlug, content: currentLines.join('\n').trimEnd() })
  }

  return sections.length > 0 ? sections : null
}

/**
 * Parses section markers from a stored comment body.
 * Returns sections in document order.
 *
 * @param {string} commentBody
 * @returns {Array<{slug: string, content: string}>}
 */
function parseStoredSections(commentBody) {
  const sections = []
  const re = /<!-- section:([a-z0-9][a-z0-9-]*) -->\n([\s\S]*?)\n<!-- \/section:\1 -->/g
  let m
  while ((m = re.exec(String(commentBody ?? ''))) !== null) {
    sections.push({ slug: m[1], content: m[2] })
  }
  return sections
}

// --- Merge -----------------------------------------------------------------------------------------------------------

/**
 * Merges incoming sections into stored sections.
 * Stored sections with a matching slug are replaced in place.
 * Incoming sections not present in stored are appended.
 *
 * @param {Array<{slug: string, content: string}>} stored
 * @param {Array<{slug: string, content: string}>} incoming
 * @returns {Array<{slug: string, content: string}>}
 */
function mergeSections(stored, incoming) {
  const incomingMap = new Map(incoming.map((s) => [s.slug, s.content]))
  const result = stored.map((s) => ({ slug: s.slug, content: incomingMap.get(s.slug) ?? s.content }))
  for (const s of incoming) {
    if (!stored.some((r) => r.slug === s.slug)) result.push(s)
  }
  return result
}

// --- Rendering -------------------------------------------------------------------------------------------------------

function renderSections(key, sections, footer) {
  const parts = [rootMarker(key)]
  for (const { slug, content } of sections) {
    parts.push(sectionOpenTag(slug))
    parts.push(content)
    parts.push(sectionCloseTag(slug))
  }
  parts.push('')
  parts.push(footer)
  return parts.join('\n')
}

function renderWholeBody(key, body, footer) {
  return [rootMarker(key), '', String(body ?? '').trimEnd(), '', footer].join('\n')
}

// --- Public API ------------------------------------------------------------------------------------------------------

/**
 * Builds the full comment body to write to GitHub.
 *
 * When existingBody is provided and incomingBody contains H1 headlines, sections are merged:
 * the caller's sections replace matching stored sections; other stored sections are preserved.
 * When existingBody is null or incomingBody has no H1 headlines, the full content is replaced.
 *
 * @param {string} key - comment-key (used for root marker)
 * @param {string} incomingBody - body input from the action caller
 * @param {string|null} [existingBody] - current comment body from GitHub, or null when creating
 * @param {Date} [now] - timestamp for the footer (injectable for tests)
 * @returns {string}
 */
function buildCommentBody(key, incomingBody, existingBody = null, now = new Date()) {
  assertNoReservedMarkers(incomingBody)

  const footer = buildFooter(now)
  const incoming = parseSections(incomingBody)

  let result
  if (incoming !== null && existingBody !== null) {
    const stored = parseStoredSections(existingBody)
    result = renderSections(key, mergeSections(stored, incoming), footer)
  } else if (incoming !== null) {
    result = renderSections(key, incoming, footer)
  } else {
    result = renderWholeBody(key, incomingBody, footer)
  }

  if (result.length > COMMENT_BODY_LIMIT) {
    throw new Error(
      `comment body would be ${result.length} characters, which exceeds the ${COMMENT_BODY_LIMIT} character limit; reduce the number or size of sections`,
    )
  }

  return result
}

module.exports = {
  COMMENT_BODY_LIMIT,
  slugify,
  parseSections,
  parseStoredSections,
  mergeSections,
  buildFooter,
  buildCommentBody,
  rootMarker,
  assertNoReservedMarkers,
  isGeneratedCommentBody,
  normalizeForComparison,
  sameGeneratedContent,
}
