'use strict'

const test = require('node:test')
const assert = require('node:assert/strict')
const { run } = require('./index.js')
const { rootMarker, parseStoredSections } = require('./comment.js')

const REPO = 'owner/repo'
const MARKER = rootMarker('default')

function baseInputs(overrides = {}) {
  return {
    token: 'ghp_test',
    prNumber: 7,
    body: '# Status\nAll good',
    commentKey: 'default',
    mode: 'upsert',
    ...overrides,
  }
}

function makeComment(id, body) {
  return { id, body, html_url: `https://github.com/owner/repo/pull/7#issuecomment-${id}` }
}

function makeApi(comments = []) {
  return {
    find: (token, repo, prNumber, marker) =>
      comments.find((c) => typeof c.body === 'string' && c.body.includes(marker)) ?? null,
    create: (token, repo, prNumber, body) => {
      const c = makeComment(comments.length + 1, body)
      comments.push(c)
      return c
    },
    update: (token, repo, id, body) => {
      const c = comments.find((c) => c.id === id)
      c.body = body
      return c
    },
  }
}

// --- upsert mode ----------------------------------------------------------------------------------------------------

test('run creates a new comment when none exists (upsert)', async () => {
  const comments = []
  const api = makeApi(comments)
  await run(baseInputs(), REPO, api)
  assert.equal(comments.length, 1)
  assert.ok(comments[0].body.includes(MARKER))
  assert.ok(comments[0].body.includes('# Status'))
})

test('run updates an existing comment when body has changed (upsert)', async () => {
  const existing = makeComment(
    1,
    `${MARKER}\n<!-- section:status -->\n# Status\nOld\n<!-- /section:status -->\n\n_Last updated: ..._`,
  )
  const comments = [existing]
  const api = makeApi(comments)
  await run(baseInputs({ body: '# Status\nNew' }), REPO, api)
  assert.equal(comments.length, 1)
  assert.ok(comments[0].body.includes('New'))
})

test('run preserves sections from other callers during an update (upsert)', async () => {
  const existingBody = [
    MARKER,
    '<!-- section:status -->',
    '# Status',
    'OK',
    '<!-- /section:status -->',
    '<!-- section:results -->',
    '# Results',
    'Passed',
    '<!-- /section:results -->',
    '',
    '_Last updated: ..._',
  ].join('\n')
  const comments = [makeComment(1, existingBody)]
  const api = makeApi(comments)

  await run(baseInputs({ body: '# Status\nUpdated' }), REPO, api)

  const stored = parseStoredSections(comments[0].body)
  assert.ok(stored.some((s) => s.slug === 'status' && s.content.includes('Updated')))
  assert.ok(stored.some((s) => s.slug === 'results'))
})

test('run calls update (not create) when a comment already exists (upsert)', async () => {
  let updateCalled = false
  let createCalled = false
  const existingBody = [
    MARKER,
    '<!-- section:status -->',
    '# Status',
    'Old',
    '<!-- /section:status -->',
    '',
    '_Last updated: ..._',
  ].join('\n')
  const existing = makeComment(1, existingBody)
  const api = {
    find: () => existing,
    create: () => {
      createCalled = true
      return makeComment(2, 'new')
    },
    update: (token, repo, id, body) => {
      updateCalled = true
      return makeComment(id, body)
    },
  }

  await run(baseInputs({ body: '# Status\nNew' }), REPO, api)
  assert.equal(updateCalled, true)
  assert.equal(createCalled, false)
})

test('run skips update when skip-unchanged is true and content did not change', async () => {
  let updateCalled = false
  const existingBody = [
    MARKER,
    '<!-- section:status -->',
    '# Status',
    'All good',
    '<!-- /section:status -->',
    '',
    '_Last updated: 2024-06-18 10:00 UTC - Generated by Remark_',
  ].join('\n')
  const existing = makeComment(1, existingBody)
  const comments = [existing]
  const api = {
    find: () => existing,
    create: () => {
      throw new Error('create should not be called')
    },
    update: () => {
      updateCalled = true
      throw new Error('update should not be called')
    },
  }

  await run(baseInputs({ skipUnchanged: true }), REPO, api)

  assert.equal(updateCalled, false)
  assert.equal(comments[0].body, existingBody)
})

test('run updates when skip-unchanged is true and content changed', async () => {
  let updateCalled = false
  const existingBody = [
    MARKER,
    '<!-- section:status -->',
    '# Status',
    'Old',
    '<!-- /section:status -->',
    '',
    '_Last updated: 2024-06-18 10:00 UTC - Generated by Remark_',
  ].join('\n')
  const existing = makeComment(1, existingBody)
  const api = {
    find: () => existing,
    create: () => {
      throw new Error('create should not be called')
    },
    update: (token, repo, id, body) => {
      updateCalled = true
      return makeComment(id, body)
    },
  }

  await run(baseInputs({ body: '# Status\nNew', skipUnchanged: true }), REPO, api)

  assert.equal(updateCalled, true)
})

// --- create mode ----------------------------------------------------------------------------------------------------

test('run always creates a new comment in create mode', async () => {
  const existingBody = `${MARKER}\ncontent`
  const comments = [makeComment(1, existingBody)]
  const api = makeApi(comments)
  await run(baseInputs({ mode: 'create' }), REPO, api)
  assert.equal(comments.length, 2)
})

test('run embeds section markers in create mode when body has H1 headlines', async () => {
  const comments = []
  const api = makeApi(comments)
  await run(baseInputs({ mode: 'create', body: '# Report\nAll done' }), REPO, api)
  assert.ok(comments[0].body.includes('<!-- section:report -->'))
})

// --- outputs --------------------------------------------------------------------------------------------------------

test('run sets comment-id and comment-url outputs', async () => {
  const comments = []
  const api = makeApi(comments)

  const originalEnv = process.env.GITHUB_OUTPUT
  const fs = require('node:fs')
  const os = require('node:os')
  const path = require('node:path')
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'remark-test-'))
  const outputFile = path.join(dir, 'out')
  process.env.GITHUB_OUTPUT = outputFile

  try {
    await run(baseInputs(), REPO, api)
    const written = fs.readFileSync(outputFile, 'utf8')
    assert.ok(written.includes('comment-id=1'))
    assert.ok(written.includes('comment-url=https://github.com'))
  } finally {
    process.env.GITHUB_OUTPUT = originalEnv ?? ''
    fs.rmSync(dir, { recursive: true, force: true })
  }
})

// --- validation -----------------------------------------------------------------------------------------------------

test('run throws when token is empty', async () => {
  await assert.rejects(() => run(baseInputs({ token: '' }), REPO, makeApi()), /github-token/)
})

test('run throws when body is empty', async () => {
  await assert.rejects(() => run(baseInputs({ body: '   ' }), REPO, makeApi()), /body input is empty/)
})

test('run throws when repo is missing', async () => {
  await assert.rejects(() => run(baseInputs(), '', makeApi()), /GITHUB_REPOSITORY/)
})
