---
name: Intent

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  intent:
    name: Intent
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Validate Intent
        uses: goeselt/intent@b0f6cb890972394cb60a0f65cf866dc76a33fef4 # v1.1.5
        with:
          pr-comment: true
